const express=require('express');
const router=express.Router();
const authController=require('../controllers/authController');
const { identifier } = require('../middlewares/identification');
router.get('/signup',authController.signup);
router.get('/login',authController.login);
router.get('/logout',identifier,authController.logout);
router.patch('/send-verification-code',identifier,authController.sendVerificationCode);
router.patch('/verify-verification-code',identifier,authController.verifyVerifcationCode);
router.patch('/change-password',identifier,authController.changePassword);
router.patch('/send-forgot-password-code',identifier,authController.sendForgotPasswordCode);
router.patch('/verify-forgot-password-code',identifier,authController.verifyForgotPasswordCode);
module.exports=router;